#TODO: update this to match default
# Tokenizer
# These paths are used to save the tokenizer and vocab. Name accordingly.
tokenizer_path: /grphome/grp_rocket/compute/dataset/tokenizers/tokenizer.model
vocab_path:  /grphome/grp_rocket/compute/dataset/tokenizers/tokenizer.vocab
pad_id: -1 # defined later by tokenizer. NOTE: padding is disabled by default, see tokenizer.py
vocab_size: -1  # defined later by tokenizer

# Paths
# default_root_dir is the root model training directory; checkpoints, predictions, and logs will be saved here.
default_root_dir: /grphome/grp_rocket/compute/runs/1-18-wikitext
# which checkpoint to use, if any, for resuming training or inference
checkpoint_path: ~

# Dataset
# Name of hf hub dataset repo, if being used. Leave blank if not : ~
hf_dataset_name: wikitext
hf_dataset_config: wikitext-2-v1
dataset_directory: /grphome/grp_rocket/compute/dataset/raw/wikitext

# Raw data file. Tokenizer expects parquet, could be changed.
raw_dataset_path: ~

# Alternatively, raw paths for train/test/val if they came split
raw_train_path: /grphome/grp_rocket/compute/dataset/raw/wikitext/train.parquet
raw_test_path: /grphome/grp_rocket/compute/dataset/raw/wikitext/test.parquet
raw_eval_path: /grphome/grp_rocket/compute/dataset/raw/wikitext/validation.parquet

# Full tokenized data file, not necessary. Must be .pkl file
tokenized_dataset_path: ~

# Dataset split, must be .pkl file
train_path: /grphome/grp_rocket/compute/dataset/tokenized/train.pkl
eval_path: /grphome/grp_rocket/compute/dataset/tokenized/eval.pkl
test_path: /grphome/grp_rocket/compute/dataset/tokenized/test.pkl

# GPU
accelerator: gpu
num_nodes: 1
devices: 8

# Train
gradient_accumulation_steps: 1
num_epochs: 10
lr: 1.0e-4 
gamma: 0.85
seed: 42
early_stopping: 5
save_top_k: 3
save_predictions_during_training: true

# Inference
inference_path: /grphome/grp_rocket/compute/dataset/raw/inference_text.txt
max_gen_len: 20

# Model
dim: 512
n_layers: 8
n_heads: 8
multiple_of: 256  # make SwiGLU hidden layer size multiple of large power of 2
norm_eps: 1.0e-5
batch_size: 32
sequence_length: 1024
dim_k: ~
dim_v: ~
